from black_scholes import BlackScholes
from heston import Heston
import matplotlib.pyplot as plt

bs_model = BlackScholes(S0=100, mu=0.05, sigma=0.2, T=1, N=252, M=100)

price_paths = bs_model.generate_data()

plt.plot(price_paths)
plt.xlabel('Time')
plt.ylabel('Price')
plt.title('Price Paths Generated by Black-Scholes Model')
plt.show()

heston_model = Heston(S0=100, mu=0.05, kappa=2, theta=0.04, sigma=0.3, rho=-0.5, v0=0.04, T=1, N=252, M=10)

price_paths = heston_model.generate_data()

plt.plot(price_paths.T)
plt.xlabel('Time')
plt.ylabel('Price')
plt.title('Price Paths Generated by Heston Model')
plt.show()
