# gan model, PathChar_GAN,RPathChar_GAN,RCGAN, COTGAN,TimeGAN 
model: BetaCVAE
encoder: CLSTMRes
conditioner: Id
decoder: CLSTMRes
prior: RealNVP
discriminator: 
dataset: Master

n_timestep: 30
n_sample: 1031

data_dim: 1
data_length: 30
latent_dim: 2
latent_length: 30
condition_dim: 1

#hyperparameters:  
optimizer: Adam
lr : 0.0005
train_batch_size: 256
eval_batch_size: 256
epochs: 500
wandb: true
seed: 0
steps_predict: 30
steps_saving: 30

# algo
beta: 0.04

# transform:
transform: log
inv_transform: exp

#conditioner hyperparameter:
C_input_dim: 0
C_hidden_dim: 0
C_num_layers: 0
C_output_dim: 0

#encoder hyperparameter:
E_input_dim: 3
E_hidden_dim: 8
E_num_layers: 2
E_output_dim: 2

#generator hyperparameter:
D_input_dim: 3
D_hidden_dim: 32
D_num_layers: 2
D_output_dim: 1

#prior hyperparameter:
P_latent_dim: 
P_num_flows: 3
P_hidden_dim: 250

device_name:

comment: 